"""add route pay rates and driver_pay_rate column

Revision ID: 6d01097f1887
Revises: fe721086c05b
Create Date: 2026-06-06 18:18:11.752631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d01097f1887'
down_revision: Union[str, Sequence[str], None] = 'fe721086c05b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_routes', sa.Column('driver_pay_rate', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_routes', 'driver_pay_rate')
    # ### end Alembic commands ###
