"""add_pricing_and_payment_fields_to_orders

Revision ID: ac965a8dc934
Revises: 4596dbc5804b
Create Date: 2025-12-21 21:40:19.512005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac965a8dc934'
down_revision: Union[str, Sequence[str], None] = '4596dbc5804b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_entries_shift_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_status'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_tenant'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_tenant_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_user'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_user_id'), table_name='time_entries')
    op.drop_index(op.f('uq_open_entry_per_user'), table_name='time_entries', postgresql_where="(status = 'OPEN'::timestatus)")
    op.drop_table('time_entries')
    op.drop_index(op.f('ix_daily_tasks_tenant_date'), table_name='daily_tasks')
    op.drop_index(op.f('ix_daily_tasks_tenant_date_completed'), table_name='daily_tasks')
    op.drop_index(op.f('ix_daily_tasks_tenant_dow'), table_name='daily_tasks')
    op.drop_index(op.f('ix_daily_tasks_tenant_role'), table_name='daily_tasks')
    op.drop_index(op.f('ix_daily_tasks_tenant_shift'), table_name='daily_tasks')
    op.drop_table('daily_tasks')
    # Add columns as nullable first
    op.add_column('customer_orders', sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('customer_orders', sa.Column('payment_status', sa.Enum('UNPAID', 'PAID', 'PARTIAL', name='paymentstatus'), nullable=True))
    op.add_column('customer_orders', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('customer_orders', sa.Column('paid_at', sa.DateTime(), nullable=True))

    # Set default values for existing orders
    op.execute("UPDATE customer_orders SET total_price = 0.00 WHERE total_price IS NULL")
    op.execute("UPDATE customer_orders SET payment_status = 'UNPAID' WHERE payment_status IS NULL")

    # Now make them NOT NULL
    op.alter_column('customer_orders', 'total_price', nullable=False)
    op.alter_column('customer_orders', 'payment_status', nullable=False)
    op.alter_column('menu_categories', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('menu_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_menu_categories_menu_id'), table_name='menu_categories')
    op.drop_index(op.f('ix_menu_categories_tenant_id'), table_name='menu_categories')
    op.drop_index(op.f('ux_menu_categories_menu_id_name'), table_name='menu_categories')
    op.drop_index(op.f('ix_menu_items_category_id'), table_name='menu_items')
    op.drop_constraint(op.f('fk_menu_items_category_id'), 'menu_items', type_='foreignkey')
    op.create_foreign_key(None, 'menu_items', 'menu_categories', ['category_id'], ['id'])
    # Add columns as nullable first
    op.add_column('order_items', sa.Column('price_at_time_of_order', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('order_items', sa.Column('item_name', sa.String(), nullable=True))

    # Populate existing order items with data from menu_items
    op.execute("""
        UPDATE order_items
        SET price_at_time_of_order = COALESCE(menu_items.price, 0.00),
            item_name = COALESCE(menu_items.name, 'Unknown Item')
        FROM menu_items
        WHERE order_items.menu_item_id = menu_items.id
    """)

    # Set defaults for any orphaned items (menu item was deleted)
    op.execute("UPDATE order_items SET price_at_time_of_order = 0.00 WHERE price_at_time_of_order IS NULL")
    op.execute("UPDATE order_items SET item_name = 'Deleted Item' WHERE item_name IS NULL")

    # Now make them NOT NULL
    op.alter_column('order_items', 'price_at_time_of_order', nullable=False)
    op.alter_column('order_items', 'item_name', nullable=False)
    op.create_unique_constraint(None, 'tenants', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='unique')
    op.drop_column('order_items', 'item_name')
    op.drop_column('order_items', 'price_at_time_of_order')
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_menu_items_category_id'), 'menu_items', 'menu_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_menu_items_category_id'), 'menu_items', ['category_id'], unique=False)
    op.create_index(op.f('ux_menu_categories_menu_id_name'), 'menu_categories', ['menu_id', 'name'], unique=True)
    op.create_index(op.f('ix_menu_categories_tenant_id'), 'menu_categories', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_menu_categories_menu_id'), 'menu_categories', ['menu_id'], unique=False)
    op.alter_column('menu_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('menu_categories', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # Drop pricing columns in reverse order
    op.drop_column('customer_orders', 'paid_at')
    op.drop_column('customer_orders', 'payment_method')
    op.drop_column('customer_orders', 'payment_status')
    op.drop_column('customer_orders', 'total_price')
    # Drop the PaymentStatus enum type
    sa.Enum('UNPAID', 'PAID', 'PARTIAL', name='paymentstatus').drop(op.get_bind())
    op.create_table('daily_tasks',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('details', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('task_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('day_of_week', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('shift_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('completed_by_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.SMALLINT(), server_default=sa.text("'0'::smallint"), autoincrement=False, nullable=False),
    sa.Column('target_qty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('progress_qty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('progress_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('day_of_week IS NULL OR day_of_week >= 1 AND day_of_week <= 7', name=op.f('ck_daily_tasks_day_of_week_range')),
    sa.CheckConstraint('progress_qty IS NULL OR progress_qty >= 0', name=op.f('ck_daily_tasks_progress_qty_nonneg')),
    sa.CheckConstraint('target_qty IS NULL OR progress_qty IS NULL OR progress_qty <= target_qty', name=op.f('ck_daily_tasks_progress_le_target')),
    sa.CheckConstraint('target_qty IS NULL OR target_qty >= 0', name=op.f('ck_daily_tasks_target_qty_nonneg')),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], name=op.f('fk_daily_tasks_completed_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('daily_tasks_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_tasks_pkey'))
    )
    op.create_index(op.f('ix_daily_tasks_tenant_shift'), 'daily_tasks', ['tenant_id', 'shift_label'], unique=False)
    op.create_index(op.f('ix_daily_tasks_tenant_role'), 'daily_tasks', ['tenant_id', 'role'], unique=False)
    op.create_index(op.f('ix_daily_tasks_tenant_dow'), 'daily_tasks', ['tenant_id', 'day_of_week'], unique=False)
    op.create_index(op.f('ix_daily_tasks_tenant_date_completed'), 'daily_tasks', ['tenant_id', 'task_date', 'is_completed'], unique=False)
    op.create_index(op.f('ix_daily_tasks_tenant_date'), 'daily_tasks', ['tenant_id', 'task_date'], unique=False)
    op.create_table('time_entries',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('shift_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('clock_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('clock_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('OPEN', 'CLOSED', 'APPROVED', 'PAID', name='timestatus'), server_default=sa.text("'OPEN'::timestatus"), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('clock_in_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('clock_out_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('clock_in_ip', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('clock_out_ip', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hourly_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('gross_pay', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_seed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.CheckConstraint('duration_minutes IS NULL OR duration_minutes >= 0', name=op.f('ck_time_entries_duration_nonneg')),
    sa.CheckConstraint('gross_pay IS NULL OR gross_pay >= 0::numeric', name=op.f('ck_time_entries_gross_nonneg')),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('time_entries_shift_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('time_entries_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('time_entries_pkey'))
    )
    op.create_index(op.f('uq_open_entry_per_user'), 'time_entries', ['tenant_id', 'user_id'], unique=True, postgresql_where="(status = 'OPEN'::timestatus)")
    op.create_index(op.f('ix_time_entries_user_id'), 'time_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_time_entries_user'), 'time_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_time_entries_tenant_id'), 'time_entries', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_time_entries_tenant'), 'time_entries', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_time_entries_status'), 'time_entries', ['status'], unique=False)
    op.create_index(op.f('ix_time_entries_shift_id'), 'time_entries', ['shift_id'], unique=False)
    # ### end Alembic commands ###
