"""add delivery route templates

Revision ID: fe721086c05b
Revises: 20260531_geofence
Create Date: 2026-06-06 17:39:52.026102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe721086c05b'
down_revision: Union[str, Sequence[str], None] = '20260531_geofence'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Template tables already exist — only add template_id FK to delivery_routes
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_routes', sa.Column('template_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'delivery_routes', 'delivery_route_templates', ['template_id'], ['id'])
    op.drop_index(op.f('idx_payments_order'), table_name='repair_order_payments')
    op.drop_index(op.f('idx_payments_tenant'), table_name='repair_order_payments')
    op.alter_column('repair_order_status_logs', 'sms_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('repair_orders', 'tracking_token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'repair_orders', ['tracking_token'])
    op.drop_index(op.f('ix_time_entries_edited'), table_name='time_entries')
    op.drop_constraint(op.f('fk_time_entries_created_by_id'), 'time_entries', type_='foreignkey')
    op.drop_constraint(op.f('fk_time_entries_edited_by_id'), 'time_entries', type_='foreignkey')
    op.create_foreign_key(None, 'time_entries', 'users', ['edited_by_id'], ['id'])
    op.create_foreign_key(None, 'time_entries', 'users', ['created_by_id'], ['id'])
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'time_entries', type_='foreignkey')
    op.drop_constraint(None, 'time_entries', type_='foreignkey')
    op.create_foreign_key(op.f('fk_time_entries_edited_by_id'), 'time_entries', 'users', ['edited_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_time_entries_created_by_id'), 'time_entries', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_time_entries_edited'), 'time_entries', ['edited_at'], unique=False)
    op.drop_constraint(None, 'repair_orders', type_='unique')
    op.alter_column('repair_orders', 'tracking_token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('repair_order_status_logs', 'sms_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('idx_payments_tenant'), 'repair_order_payments', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_payments_order'), 'repair_order_payments', ['repair_order_id'], unique=False)
    op.drop_constraint(None, 'delivery_routes', type_='foreignkey')
    op.drop_column('delivery_routes', 'template_id')
    # ### end Alembic commands ###
